### ISSUE TITLE
The final result?

### ISSUE THREAD

**Issue by SoonyangZhang** [qhb1001/SDN-Simulation#1]
Remarkable work and what's the conclusion finally? 
I am not quite familiar with omnetplusplus, and run simulation experiments on ns3. With to many tcp flows, the packets level simulator will last quite long time due to too many discrete events.  Does omnetplusplus suffer such problem?

**Comment by qhb1001** [comment]
Thanks for your question:) and it is my bad that not include the result into the project, I will upload one video for working process and some data documents for analysis recently. Here is the quick answer. 

First, about the result. Here are some screen shots of the outcome. 

[network topology]
![image](https://user-images.githubusercontent.com/38253329/54065112-c9b1bc80-4256-11e9-897f-828bbf15b60b.png)

[data analysis]
`Count` means the number of the messages that has been transported to this nodes 
`Mean` means the average hops of the route plan
![image](https://user-images.githubusercontent.com/38253329/54065153-4cd31280-4257-11e9-9126-bb005911fae2.png)

Second, about the omnet++ platform. This is a very simple demo without the implementation of queuing, multi-thread, tcp protocol, etc.. The project only serves the purpose to explore the effectiveness of the reinforcement algorithm. And based on that, it is very fast. As you can see about the [data analysis] section, there're about 10,000 messages that have been transported which only spend about 3s. 

Hope it helps.

**Comment by SoonyangZhang** [comment]
Thanks for the reply. I read a similar paper (Experience-driven Networking: A Deep Reinforcement Learning based Approach, 2018 infocom) applying reinforce learning approach in routing before. I am quite interested such area, but not familiar.
